package com.codegym.task.task29.task2913;

import java.util.Random;

/* 
Replace recursion

*/

//Replace recursion
//Two integers, A and B, are randomly generated by the program. You need to display all integers from A to B inclusive,
// in ascending order, if A is less than B, or in descending order otherwise.
//
//The task is implemented using recursion.
//Sometimes the program throws an Exception (java.lang.StackOverflowError) on "main" thread.
//
//Here's your task: rewrite the code so that it does not use recursion.
//Rename the recursion() method to getAllNumbersBetween().
//
//
//Requirements:
//1. The recursion() method must be renamed to getAllNumbersBetween().
//2. There should not be recursive calls in any method of the Solution class.
//3. There must not be a space at the end of the output line with the sequence of numbers.
//4. The behavior of the program should remain the same.
//5. Don't change the main() method.

public class Solution {
    private static int numberA;
    private static int numberB;

    public static String getAllNumbersBetween(int a, int b) {

        StringBuilder result = new StringBuilder();

        if (a < b){

            for (int i = a; i <= b; i++){
                if (i != b) result.append(i).append(" ");
                else result.append(i);
            }
            return result.toString();

        } else if (a > b){

            for (int i = a; i >= b; i--){
                if (i != b) result.append(i).append(" ");
                else result.append(i);
            }
            return result.toString();

        } else {
            return result.append(a).toString();
        }
    }

    public static void main(String[] args) {
        Random random = new Random();
        numberA = random.nextInt(1000);
        numberB = random.nextInt(1000);
        System.out.println(getAllNumbersBetween(numberA, numberB));
        System.out.println(getAllNumbersBetween(numberB, numberA));
    }
}